### PR TITLE
Make nodes draggable for mapping activities.

### PR DESCRIPTION
**Pull request by phuff**
I wanted to make things draggable so I could move them around during mapping activities, so I added some dragging.

### CODE REVIEW

**Comment by phuff** [comment]
I added in an "editable" mode, so by default things aren't draggable, but if you put "mode": "editable" into your json, then you can do a mapping activity.  It'll be possible to add some more things to the editable mode over time.

**Comment by cioportfolio** [comment]
Hi,

I really appreciate you putting your time and energy into this, thank you. The intention of this repository was to demonstrate the idea of capturing the logic of a map in script form rather than to make a script editor. Since I started work on this others have created better map script languages and tools so I hope you understand if I don't merge this pull request. Let me know what you think.

**Comment by phuff** [comment]
Oh, that's just fine if you don't merge, I mostly liked this because it was very simple, but I thought for a mapping activity it would be good to be able to move things around and still get a copy of the script afterwards.

Are there other scripting languages and tools that this reminds you of that I could look at?

**Comment by cioportfolio** [comment]
This is a good source: https://github.com/wardley-maps-community/awesome-wardley-maps#mapping-1

**Pull request closed without merging**
